"use client";
import { useMemo, useRef, useState } from "react";
type Photo={id:string;description:string;lat?:number;lng?:number;source?:string;color:string};
const seed:Photo[]=[
{id:"P001",description:"工區上游既有水圳及周邊農耕環境",lat:24.123456,lng:120.123456,source:"EXIF",color:"field-a"},
{id:"P002",description:"既有水門設施與護岸銜接處",lat:24.123501,lng:120.123802,source:"EXIF",color:"field-b"},
{id:"P003",description:"下游排水渠道現況",color:"field-c"}];
export default function Home(){
 const[photos,setPhotos]=useState(seed),[selected,setSelected]=useState<Photo|null>(null),[notice,setNotice]=useState("");const fileRef=useRef<HTMLInputElement>(null);const missing=useMemo(()=>photos.filter(p=>!p.lat).length,[photos]);
 function addFiles(files:FileList|null){if(!files?.length)return;const additions=Array.from(files).map((f,i)=>({id:`P${String(photos.length+i+1).padStart(3,"0")}`,description:f.name.replace(/\.[^.]+$/, ""),color:["field-a","field-b","field-c"][i%3]}));setPhotos(c=>[...c,...additions]);setNotice(`已加入 ${additions.length} 張照片，可稍後補寫說明與座標`)}
 function savePhoto(next:Photo){setPhotos(c=>c.map(p=>p.id===next.id?next:p));setSelected(null);setNotice(`${next.id} 已儲存，最後修改者：陳怡君`)}
 return <main className="app-shell">
 <header className="topbar"><button className="icon-button" aria-label="返回案件列表">←</button><div className="title-block"><span className="eyebrow">頂五厘制水門改建工程</span><h1>施工中現勘</h1></div><button className="avatar" aria-label="帳號：陳怡君">陳</button></header>
 <section className="survey-card"><div className="date-badge"><b>17</b><span>8月・2026</span></div><div><p className="muted">現勘日期</p><h2>2026 年 8 月 17 日</h2><p>記錄施工範圍、既有水路與周邊環境現況。</p></div><button className="text-button" onClick={()=>setNotice("現勘說明已開啟編輯")}>編輯</button></section>
 <section className="actions"><button className="primary" onClick={()=>fileRef.current?.click()}><span>＋</span> 拍照</button><button className="secondary" onClick={()=>fileRef.current?.click()}><span>▧</span> 選取照片</button><input ref={fileRef} hidden type="file" accept="image/*" multiple onChange={e=>addFiles(e.target.files)}/></section>
 {notice&&<div className="notice" role="status"><span>✓</span>{notice}<button onClick={()=>setNotice("")} aria-label="關閉">×</button></div>}
 <section className="photo-section"><div className="section-heading"><div><p className="eyebrow">現勘照片</p><h2>{photos.length} 張照片</h2></div><div className="sync"><i/> 已同步</div></div>
 {missing>0&&<button className="gps-alert" onClick={()=>setSelected(photos.find(p=>!p.lat)||null)}><span>⌖</span><div><b>{missing} 張照片尚無座標</b><small>可使用目前位置或手動補上</small></div><strong>處理 →</strong></button>}
 <div className="photo-grid">{photos.map(p=><article className="photo-card" key={p.id} onClick={()=>setSelected(p)}><div className={`photo-visual ${p.color}`}><span>{p.id}</span><button aria-label={`編輯 ${p.id}`}>•••</button></div><div className="photo-copy"><p>{p.description||"尚未填寫照片說明"}</p>{p.lat?<small className="has-gps">● {p.lat.toFixed(6)}, {p.lng?.toFixed(6)}</small>:<small className="no-gps">○ 無座標・點擊補上</small>}</div></article>)}</div></section>
 <nav className="bottom-nav"><button>⌂<span>案件</span></button><button className="active">▤<span>現勘</span></button><button>◎<span>帳號</span></button></nav>
 {selected&&<Editor photo={selected} onClose={()=>setSelected(null)} onSave={savePhoto}/>}</main>}
function Editor({photo,onClose,onSave}:{photo:Photo;onClose:()=>void;onSave:(p:Photo)=>void}){const[draft,setDraft]=useState(photo);function locate(){navigator.geolocation?.getCurrentPosition(pos=>setDraft({...draft,lat:pos.coords.latitude,lng:pos.coords.longitude,source:"DEVICE"}))}return <div className="modal-backdrop" onMouseDown={onClose}><section className="editor" onMouseDown={e=>e.stopPropagation()}><div className="drag"/><div className="editor-head"><div><p className="eyebrow">照片資料</p><h2>{photo.id}</h2></div><button onClick={onClose}>×</button></div><div className={`editor-photo ${photo.color}`}><span>{photo.id}</span></div><label>照片說明<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><div className="coordinate-head"><label>座標</label><button onClick={locate}>⌖ 使用目前位置</button></div><div className="coordinates"><label>緯度<input inputMode="decimal" value={draft.lat??""} placeholder="24.123456" onChange={e=>setDraft({...draft,lat:Number(e.target.value),source:"MANUAL"})}/></label><label>經度<input inputMode="decimal" value={draft.lng??""} placeholder="120.123456" onChange={e=>setDraft({...draft,lng:Number(e.target.value),source:"MANUAL"})}/></label></div><div className="meta"><span>座標來源 <b>{draft.source||"尚無座標"}</b></span><span>上傳者 <b>王志明</b></span></div><button className="save" onClick={()=>onSave(draft)}>儲存修改</button></section></div>}
